// <copyright file=RequestInput company=E2E Robotics>
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author>Saurabh Mundhe</author>
// <date> 03-10-2018 16:02:51</date>
// <summary></summary>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace RobotLibrary
{
    //[DataContract]
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30219.1")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public class RequestInput
    //{
    //    [DataMember]
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string RequestNumber { get; set; } //provided by end user

    //    [DataMember]
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public int RequestTimeoutSLAInSeconds { get; set; } //0 = no sla

    //    [DataMember]
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string TenantName { get; set; }

    //    [DataMember]
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string AutomationGroupName { get; set; }
    //    [DataMember]
    //    [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string AutomationProcessName { get; set; }
    //    [DataMember]
    //    [System.Xml.Serialization.XmlElementAttribute()]
    //    public List<string> InputSearchParameters { get; set; }
    //     [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string TransactionLog { get; set; }//this field will not be a data member and value will be generated by listener
    //     [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string ErrorDetails { get; set; }//this field will not be a data member and value will be generated by listener
    //     [System.Xml.Serialization.XmlAttributeAttribute()]
    //    public string UniqueRequestNumber { get; set; }//this field will not be a data member and value will be generated by listener
    //}

    
}
