//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRULib.Localiz {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRULib.Localiz.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove MRU Entry.
        /// </summary>
        public static string CMD_MRU_RemoveEntry_Description {
            get {
                return ResourceManager.GetString("CMD_MRU_RemoveEntry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path to clipboard.
        /// </summary>
        public static string STR_AppCommand_CopyFileURLToClipboard {
            get {
                return ResourceManager.GetString("STR_AppCommand_CopyFileURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File....
        /// </summary>
        public static string STR_LOAD_FILE {
            get {
                return ResourceManager.GetString("STR_LOAD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads the selected file ....
        /// </summary>
        public static string STR_LOAD_FILE_TT {
            get {
                return ResourceManager.GetString("STR_LOAD_FILE_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path to Clipboard.
        /// </summary>
        public static string STR_MRU_MENUITEM_COPYURL {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_COPYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in containing Folder.
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenInContainingFolder {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenInContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Windows Application....
        /// </summary>
        public static string STR_MRU_MENUITEM_OpenWithWindowsApp {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_OpenWithWindowsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string STR_MRU_MENUITEM_Remove {
            get {
                return ResourceManager.GetString("STR_MRU_MENUITEM_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string STR_REMOVE_ALL_ITEMS {
            get {
                return ResourceManager.GetString("STR_REMOVE_ALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes all items in the list..
        /// </summary>
        public static string STR_REMOVE_ALL_ITEMS_TT {
            get {
                return ResourceManager.GetString("STR_REMOVE_ALL_ITEMS_TT", resourceCulture);
            }
        }
    }
}
